create table refresh_tokens (
    id bigint generated by default as identity,
    user_id bigint not null references users (id) on delete cascade,
    token_hash varchar(64) not null,
    family_id varchar(36) not null,
    token_version integer not null,
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    used_at timestamp(6),
    primary key (id),
    constraint uk_refresh_tokens_hash unique (token_hash)
);
create index idx_refresh_tokens_user on refresh_tokens (user_id);
create index idx_refresh_tokens_family on refresh_tokens (family_id);

-- Two-factor sign-in (TOTP, RFC 6238). The secret is stored only once confirmed;
-- recovery codes are SHA-256 digests, comma separated, removed when used.
alter table users add column totp_enabled boolean not null default false;
alter table users add column totp_secret varchar(64);
alter table users add column totp_last_step bigint;
alter table users add column totp_recovery_codes varchar(1000);
