
    create table accounts (
        balance numeric(15,2) not null,
        exclude_from_reports boolean not null,
        exclude_from_summary boolean not null,
        sort_order integer not null,
        start_balance numeric(15,2) not null,
        created_at TIMESTAMP not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        account_group varchar(255),
        account_name varchar(255) not null,
        account_number varchar(255) not null unique,
        account_type varchar(255) not null check ((account_type in ('BANK','CASH','ASSET','CREDIT_CARD','LIABILITY','CURRENT','SAVINGS'))),
        currency varchar(255) not null,
        institution varchar(255),
        primary key (id)
    );

    create table assets (
        current_price numeric(19,8),
        id bigint generated by default as identity,
        last_update timestamp(6),
        user_id bigint not null,
        currency varchar(255),
        name varchar(255) not null,
        symbol varchar(255) not null,
        type varchar(255) not null check ((type in ('STOCK','ETF','CRYPTO'))),
        primary key (id)
    );

    create table categories (
        id bigint generated by default as identity,
        parent_id bigint,
        user_id bigint not null,
        name varchar(255) not null,
        type varchar(255) not null check ((type in ('EXPENSE','INCOME'))),
        primary key (id),
        unique (user_id, parent_id, name)
    );

    create table currencies (
        frac_digits integer not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        code varchar(255) not null,
        decimal_char varchar(255),
        grouping_char varchar(255),
        name varchar(255) not null,
        symbol varchar(255) not null,
        primary key (id)
    );

    create table global_settings (
        setting_key varchar(255) not null,
        setting_value varchar(255) not null,
        primary key (setting_key)
    );

    create table payees (
        default_category_id bigint,
        id bigint generated by default as identity,
        user_id bigint not null,
        default_memo varchar(255),
        default_payment_method varchar(255) check ((default_payment_method in ('NONE','DEBIT_CARD','CASH','BANK_TRANSFER','STANDING_ORDER','ELECTRONIC_PAYMENT','FI_FEE','CARD_TRANSACTION','TRADE','TRANSFER','REWARD','INTEREST'))),
        default_tags varchar(255),
        name varchar(255) not null,
        notes varchar(255),
        primary key (id)
    );

    create table scheduled_transactions (
        amount numeric(15,2) not null,
        enabled boolean not null,
        recurrence_value integer,
        units numeric(19,8),
        asset_id bigint,
        category_id bigint,
        from_account_id bigint,
        id bigint generated by default as identity,
        next_occurrence timestamp(6) not null,
        to_account_id bigint,
        user_id bigint not null,
        memo varchar(255),
        number varchar(255),
        payee varchar(255),
        payment_method varchar(255) check ((payment_method in ('NONE','DEBIT_CARD','CASH','BANK_TRANSFER','STANDING_ORDER','ELECTRONIC_PAYMENT','FI_FEE','CARD_TRANSACTION','TRADE','TRANSFER','REWARD','INTEREST'))),
        recurrence_pattern varchar(255) not null check ((recurrence_pattern in ('DAILY','WEEKLY','MONTHLY','MONTHLY_LAST_DAY','YEARLY','EVERY_FRIDAY','EVERY_SATURDAY','EVERY_WEEKDAY','BI_WEEKLY'))),
        tags varchar(255),
        type varchar(255) not null check ((type in ('EXPENSE','INCOME','TRANSFER'))),
        primary key (id)
    );

    create table tags (
        id bigint generated by default as identity,
        user_id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table transaction_splits (
        amount numeric(15,2) not null,
        category_id bigint not null,
        id bigint generated by default as identity,
        transaction_id bigint not null,
        memo varchar(255),
        primary key (id)
    );

    create table transactions (
        amount numeric(15,2) not null,
        sort_order integer not null,
        units numeric(19,8),
        asset_id bigint,
        category_id bigint,
        from_account_id bigint,
        id bigint generated by default as identity,
        to_account_id bigint,
        transaction_date TIMESTAMP not null,
        memo varchar(255),
        number varchar(255),
        payee varchar(255),
        payment_method varchar(255) check ((payment_method in ('NONE','DEBIT_CARD','CASH','BANK_TRANSFER','STANDING_ORDER','ELECTRONIC_PAYMENT','FI_FEE','CARD_TRANSACTION','TRADE','TRANSFER','REWARD','INTEREST'))),
        status varchar(255) not null check ((status in ('PENDING','COMPLETED','FAILED'))),
        tags varchar(255),
        type varchar(255) not null check ((type in ('EXPENSE','INCOME','TRANSFER'))),
        primary key (id)
    );

    create table user_roles (
        user_id bigint not null,
        role varchar(255)
    );

    create table users (
        api_enabled boolean not null,
        dark_mode boolean not null,
        default_currency varchar(3),
        enabled boolean not null,
        created_at timestamp(6) not null,
        default_vehicle_category_id bigint,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        locale varchar(255),
        password varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists accounts 
       add constraint FKnjuop33mo69pd79ctplkck40n 
       foreign key (user_id) 
       references users;

    alter table if exists assets 
       add constraint FKi37wgdksbwub2fd1g8orrh975 
       foreign key (user_id) 
       references users;

    alter table if exists categories 
       add constraint FKsaok720gsu4u2wrgbk10b5n8d 
       foreign key (parent_id) 
       references categories;

    alter table if exists categories 
       add constraint FKghuylkwuedgl2qahxjt8g41kb 
       foreign key (user_id) 
       references users;

    alter table if exists currencies 
       add constraint FK3cklxf84tofpqc4ryed9w9cjt 
       foreign key (user_id) 
       references users;

    alter table if exists payees 
       add constraint FKekt0f3m13ayvbj8uxekwq5l5h 
       foreign key (default_category_id) 
       references categories;

    alter table if exists payees 
       add constraint FKk1oqialg8ruv33wv7esvn8e5n 
       foreign key (user_id) 
       references users;

    alter table if exists scheduled_transactions 
       add constraint FK839ji4jk2exbqyct6n7rh8op3 
       foreign key (asset_id) 
       references assets;

    alter table if exists scheduled_transactions 
       add constraint FK2fw0p1qweunxn5e55e51q5ayw 
       foreign key (category_id) 
       references categories;

    alter table if exists scheduled_transactions 
       add constraint FKsigba7flfhm4jbu3m5mvqjp60 
       foreign key (from_account_id) 
       references accounts;

    alter table if exists scheduled_transactions 
       add constraint FKoii4a4rvdhtatn4bru4oilaje 
       foreign key (to_account_id) 
       references accounts;

    alter table if exists scheduled_transactions 
       add constraint FK7eoo6e5xu2sfxwx17rrts9d91 
       foreign key (user_id) 
       references users;

    alter table if exists tags 
       add constraint FKpsynysaxl7cyw8mr5c8xevneg 
       foreign key (user_id) 
       references users;

    alter table if exists transaction_splits 
       add constraint FKpmxddpg7l37pdpt93qgc1v26o 
       foreign key (category_id) 
       references categories;

    alter table if exists transaction_splits 
       add constraint FK9r7pdw2xyqk7qhh28jj7dttd7 
       foreign key (transaction_id) 
       references transactions;

    alter table if exists transactions 
       add constraint FKpxknnk31w8gmwnnir0kg21mv7 
       foreign key (asset_id) 
       references assets;

    alter table if exists transactions 
       add constraint FKsqqi7sneo04kast0o138h19mv 
       foreign key (category_id) 
       references categories;

    alter table if exists transactions 
       add constraint FK7i7kboanveneetad7jyhbr0a7 
       foreign key (from_account_id) 
       references accounts;

    alter table if exists transactions 
       add constraint FKra0an432c5wjo76mojluk0v28 
       foreign key (to_account_id) 
       references accounts;

    alter table if exists user_roles 
       add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
       foreign key (user_id) 
       references users;
