create table budgets (
    id bigint generated by default as identity,
    user_id bigint not null,
    category_id bigint not null,
    monthly_limit numeric(15,2) not null,
    active boolean not null,
    primary key (id),
    constraint uk_budget_user_category unique (user_id, category_id)
);

alter table if exists budgets
    add constraint fk_budgets_user foreign key (user_id) references users;

alter table if exists budgets
    add constraint fk_budgets_category foreign key (category_id) references categories;
