create table saved_views (
    id bigint generated by default as identity,
    user_id bigint not null,
    name varchar(100) not null,
    params varchar(2000) not null,
    created_at timestamp(6) not null,
    primary key (id),
    constraint uk_saved_view_user_name unique (user_id, name)
);

alter table if exists saved_views
    add constraint fk_saved_views_user foreign key (user_id) references users;
