create table audit_log (
    id bigint generated by default as identity,
    user_id bigint,
    username varchar(100) not null,
    ts timestamp(6) not null,
    entity_type varchar(40) not null,
    entity_id bigint,
    action varchar(20) not null,
    details varchar(500),
    primary key (id)
);

create index idx_audit_log_ts on audit_log (ts);
