-- Which transaction a client's Idempotency-Key created, so a retried POST
-- returns it instead of creating a duplicate.
create table idempotency_keys (
    id bigint generated by default as identity,
    user_id bigint not null,
    idem_key varchar(100) not null,
    transaction_id bigint not null,
    created_at timestamp(6) not null,
    primary key (id),
    constraint uk_idempotency_user_key unique (user_id, idem_key)
);
